### ISSUE TITLE
Cargo recompiles unicornafl every time

### ISSUE THREAD

**Issue by FelixBrakel** [AFLplusplus/unicornafl#2]
When adding unicornafl to the cargo dependencies in the following way:

```toml
[dependencies]
unicornafl = { git = "https://github.com/AFLplusplus/unicornafl", version="1.1.0" }
```
It causes unicornafl to be recompiled every time. Possibly a mistake in the build.rs or maybe an error in cargo?
